  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar migraciones
        run: |
          cd dashboard
          export PYTHONPATH=$PWD
          python manage.py migrate

      - name: Ejecutar tests Django
        run: |
          cd dashboard
          export PYTHONPATH=$PWD
          python manage.py test
